packages:
  - 'apps/*'
  - 'packages/*'
  - 'pages/*'

catalog:
  react: 19.2.0
  react-dom: 19.2.0
  styled-components: 6.1.19
  react-router: 7.9.6
  "@types/react": 19.2.6
  "@types/react-dom": 19.2.3
  eslint: 9.39.1
  prettier: 3.7.2
  typescript: 5.5.3

