import React from "react";

// @mf-types directory is autogenerated when you start the server
import RemoteButtonType from "ui_components/Button";

const RemoteButton = React.lazy(
  () => import("ui_components/Button")
) as unknown as typeof RemoteButtonType;

const App = () => (
  <div>
    <h1>Typescript</h1>
    <h2>App 1</h2>
    <React.Suspense fallback="Loading Button">
      <RemoteButton size="large">Remote Large Button</RemoteButton>
      <br />
      <RemoteButton size="small">Remote Small Button</RemoteButton>
      <RemoteButton size="small" isMobile>Remote Small Button</RemoteButton>
    </React.Suspense>
  </div>
);

export default App;
